apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xdg-data-user01
  namespace: ide
  labels:
    app: xdg-data-user01
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-user01
  namespace: ide
  labels:
    app: workspace-user01
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi